{
 "title": "Rebuilder dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Number of rebuild configs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(rebuilder_stats)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "#updated images",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rebuilder_stats{updated=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#src failures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rebuilder_stats{srcOK=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#dst failures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rebuilder_stats{dstOK=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#build failures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rebuilder_stats{buildOK=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#restart failures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rebuilder_stats{actionOK=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rebuilder stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Rebuilt images",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rebuilder_stats{updated=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed builds",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rebuilder_stats{buildOK=\"false\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rebuilder_stats{dstOK=\"false\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rebuilder_stats{srcOK=\"false\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All builds",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    { "expr": "rebuilder_stats{}", "legendFormat": "__auto" }
   ]
  }
 ]
}